select store_id , store_name , location , most_exp_product , cheapest_product , imbalance_ratio from (select f2.store_id , store_name ,location, f2.min_price , f2.max_price , imbalance_ratio , product_name as most_exp_product , cheapest_product from (select f1.store_id , store_name ,location, f1.min_price , f1.max_price , imbalance_ratio , product_name as cheapest_product from(select stores.store_id , stores.store_name , location, min_price , max_price , imbalance_ratio from(select store_id , store_name , min_price , max_price , ROUND((min_quan::numeric/max_quan), 2) as imbalance_ratio from
(select store_id , store_name , min_price , max_price , min_quan , max_quan from(
(select two.store_id as store1, store_name as name1 ,  min_price as m_p1, max_price as max_p1,quantity as min_quan, products_count from (select store_id , store_name , min(price) as min_price , max(price) as max_price , count(distinct product_name) as products_count from(select stores.store_id , store_name , location , product_name , quantity , price from stores join inventory on stores.store_id = inventory.store_id ) as one group by store_id , store_name having count(distinct product_name) >= 3 ) as two join inventory on two.store_id = inventory.store_id and two.min_price = inventory.price) as min_quantity

join 

(select four.store_id , store_name ,  min_price , max_price ,quantity as max_quan, products_count from (select store_id , store_name , min(price) as min_price , max(price) as max_price , count(distinct product_name) as products_count from(select stores.store_id , store_name , location , product_name , quantity , price from stores join inventory on stores.store_id = inventory.store_id ) as three group by store_id , store_name having count(distinct product_name) >= 3 ) as four join inventory on four.store_id = inventory.store_id and four.max_price = inventory.price ) as max_quantity

on min_quantity.store1 = max_quantity.store_id
) as res where max_quan < min_quan ) final1 ) as final2 join stores on final2.store_id = stores.store_id )as f1 join inventory on f1.store_id = inventory.store_id and f1.min_price = inventory.price) as f2 join inventory on f2.store_id = inventory.store_id and f2.max_price = inventory.price ) as final_result order by imbalance_ratio desc , store_name ;
